create table prompt
(
    answer   varchar not null,
    thread   varchar not null,
    question varchar,
    promptid integer generated always as identity
        constraint promptid
            primary key,
    vectors  double precision[]
);

alter table prompt
    owner to postgres;

create table images
(
    imageurl varchar,
    id       bigint generated by default as identity,
    prompt   varchar
);

alter table images
    owner to postgres;

create table "user"
(
    userid       integer generated always as identity
        constraint userid
            primary key,
    email        text,
    password     text,
    isloggedin   boolean,
    updateondate timestamp with time zone
);

alter table "user"
    owner to postgres;

create table contact
(
    contactid integer generated always as identity
        primary key,
    firstname text,
    lastname  text,
    petname   text,
    phone     varchar(10),
    address   varchar(255),
    userid    integer
        constraint userid
            references "user",
    orderid   integer
);

alter table contact
    owner to postgres;

create index fki_userid
    on contact (contactid);

create index fki_orderid
    on contact (orderid);

create table tag
(
    tagid     integer generated always as identity
        primary key,
    tagtype   text,
    hasdesign boolean,
    hasqrcode boolean
);

alter table tag
    owner to postgres;

create table "order"
(
    orderid     integer generated always as identity
        primary key,
    tagid       integer
        constraint tagid
            references tag,
    orderamount money,
    contactid   integer
        constraint contactid
            references contact
);

alter table "order"
    owner to postgres;

alter table contact
    add constraint orderid
        foreign key (orderid) references "order";

create index fki_tagid
    on "order" (tagid);

create index fki_contactid
    on "order" (contactid);


