openapi: 3.0.0
info:
  title: LaserTags API
  version: 1.0.0
  description: |
    API for LaserTags - Pet ID tags with QR code laser engraving.
    Customers can optionally store their contact information for QR code generation.
  contact:
    name: API Support
    email: erbows@collar-culture.com
servers:
  - url: http://localhost:3003
    description: Local Development Server

paths:
  /getContact/{contactid}:
    get:
      summary: Get contact by ID
      description: Retrieve contact information by contact ID for QR code generation
      tags:
        - Contact
      parameters:
        - in: path
          name: contactid
          required: true
          schema:
            type: integer
            minimum: 1
          description: The unique contact identifier
          example: 123
      responses:
        '201':
          description: Contact found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactResponse'
        '204':
          description: Contact not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  contact:
                    type: object
                    nullable: true
                  contactid:
                    type: integer
                  exists:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 204
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /saveContact:
    post:
      summary: Save new contact
      description: |
        Create a new contact record for QR code engraving on pet ID tags.
        Contact ID is auto-generated by the database.
      tags:
        - Contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInput'
            example:
              firstname: "John"
              lastname: "Doe"
              petname: "Max"
              phone: "5551234567"
              address: "123 Main St, City, ST 12345"
      responses:
        '201':
          description: Contact saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                contactid: 123
                firstname: "John"
                lastname: "Doe"
                petname: "Max"
                phone: "5551234567"
                address: "123 Main St, City, ST 12345"
                orderid: null
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /updateContact:
    post:
      summary: Update existing contact
      description: Update contact information for an existing record
      tags:
        - Contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactUpdate'
            example:
              contactid: 123
              firstname: "John"
              lastname: "Smith"
              petname: "Max"
              phone: "5551234567"
              address: "456 New St, City, ST 12345"
      responses:
        '200':
          description: Contact updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  contactUpdated:
                    type: boolean
                    example: true
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /stripePayment:
    post:
      summary: Create payment intent
      description: |
        Create a Stripe Payment Intent for processing laser tag orders.
        Returns a client_secret that can be used with Stripe.js in the frontend.
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentIntentInput'
            example:
              amount: 1999
              currency: "usd"
              contactid: 123
              orderid: 456
      responses:
        '200':
          description: Payment intent created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntentResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /stripePayment/{paymentIntentId}:
    get:
      summary: Retrieve payment intent
      description: Get the status of a payment intent by its ID
      tags:
        - Payment
      parameters:
        - in: path
          name: paymentIntentId
          required: true
          schema:
            type: string
          description: The payment intent ID
          example: "pi_1234567890"
      responses:
        '200':
          description: Payment intent retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntentDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /stripePayment/confirm:
    post:
      summary: Confirm payment intent
      description: Confirm a payment intent with payment method details
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmPaymentInput'
            example:
              paymentIntentId: "pi_1234567890"
              paymentMethod: "pm_1234567890"
      responses:
        '200':
          description: Payment confirmed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntentDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sendEmail:
    post:
      summary: Send email
      description: Send an email using Gmail API
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailInput'
            example:
              from: "customer@example.com"
              to: "support@lasertags.com"
              subject: "Order Inquiry"
              message: "I have a question about my order"
      responses:
        '200':
          description: Email sent successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Email Sent!"
        '500':
          description: Failed to send email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Contact:
      type: object
      properties:
        contactid:
          type: integer
          description: Unique contact identifier (auto-generated)
          example: 123
        firstname:
          type: string
          nullable: true
          description: Customer first name
          example: "John"
        lastname:
          type: string
          nullable: true
          description: Customer last name
          example: "Doe"
        petname:
          type: string
          nullable: true
          description: Pet name for the ID tag
          example: "Max"
        phone:
          type: string
          nullable: true
          description: Customer phone number
          example: "5551234567"
        address:
          type: string
          nullable: true
          description: Customer address
          example: "123 Main St, City, ST 12345"
        orderid:
          type: integer
          nullable: true
          description: Associated order identifier
          example: 456
      required:
        - contactid

    ContactInput:
      type: object
      properties:
        firstname:
          type: string
          nullable: true
          description: Customer first name
          example: "John"
        lastname:
          type: string
          nullable: true
          description: Customer last name
          example: "Doe"
        petname:
          type: string
          nullable: true
          description: Pet name for the ID tag
          example: "Max"
        phone:
          type: string
          nullable: true
          description: Customer phone number
          example: "5551234567"
        address:
          type: string
          nullable: true
          description: Customer address
          example: "123 Main St, City, ST 12345"

    ContactUpdate:
      type: object
      properties:
        contactid:
          type: integer
          description: Contact ID to update
          example: 123
        firstname:
          type: string
          nullable: true
          description: Customer first name
          example: "John"
        lastname:
          type: string
          nullable: true
          description: Customer last name
          example: "Smith"
        petname:
          type: string
          nullable: true
          description: Pet name for the ID tag
          example: "Max"
        phone:
          type: string
          nullable: true
          description: Customer phone number
          example: "5551234567"
        address:
          type: string
          nullable: true
          description: Customer address
          example: "456 New St, City, ST 12345"
      required:
        - contactid

    ContactResponse:
      type: object
      properties:
        contact:
          $ref: '#/components/schemas/Contact'
        exists:
          type: boolean
          description: Whether the contact exists
          example: true
        status:
          type: integer
          description: HTTP status code
          example: 201

    EmailInput:
      type: object
      properties:
        from:
          type: string
          description: Sender email address
          example: "customer@example.com"
        to:
          type: string
          description: Recipient email address
          example: "support@lasertags.com"
        subject:
          type: string
          description: Email subject
          example: "Order Inquiry"
        message:
          type: string
          description: Email message body
          example: "I have a question about my order"
      required:
        - from
        - to
        - subject
        - message

    PaymentIntentInput:
      type: object
      properties:
        amount:
          type: integer
          description: Amount in cents (e.g., 1999 = $19.99)
          minimum: 1
          example: 1999
        currency:
          type: string
          description: Currency code (3-letter ISO code)
          default: "usd"
          example: "usd"
        contactid:
          type: integer
          nullable: true
          description: Associated contact ID
          example: 123
        orderid:
          type: integer
          nullable: true
          description: Associated order ID
          example: 456
      required:
        - amount

    PaymentIntentResponse:
      type: object
      properties:
        clientSecret:
          type: string
          description: Client secret for Stripe.js integration
          example: "pi_1234567890_secret_xyz"
        paymentIntentId:
          type: string
          description: Payment intent ID
          example: "pi_1234567890"
        amount:
          type: integer
          description: Amount in cents
          example: 1999
        currency:
          type: string
          description: Currency code
          example: "usd"
        status:
          type: string
          description: Payment intent status
          enum: [requires_payment_method, requires_confirmation, requires_action, processing, requires_capture, canceled, succeeded]
          example: "requires_payment_method"

    PaymentIntentDetails:
      type: object
      properties:
        paymentIntentId:
          type: string
          description: Payment intent ID
          example: "pi_1234567890"
        amount:
          type: integer
          description: Amount in cents
          example: 1999
        currency:
          type: string
          description: Currency code
          example: "usd"
        status:
          type: string
          description: Payment intent status
          example: "succeeded"
        clientSecret:
          type: string
          description: Client secret
          example: "pi_1234567890_secret_xyz"
        metadata:
          type: object
          description: Additional metadata
          properties:
            contactid:
              type: string
            orderid:
              type: string

    ConfirmPaymentInput:
      type: object
      properties:
        paymentIntentId:
          type: string
          description: Payment intent ID to confirm
          example: "pi_1234567890"
        paymentMethod:
          type: string
          description: Payment method ID
          example: "pm_1234567890"
      required:
        - paymentIntentId
        - paymentMethod

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Internal server error"
        error:
          type: string
          description: Error details

tags:
  - name: Contact
    description: Contact management for QR code laser engraving
  - name: Payment
    description: Payment processing endpoints
  - name: Email
    description: Email sending functionality
